import { UserController } from "./controller/UserController";
import { ReceiverController } from "./controller/ReceiverController";
import { EventController } from "./controller/EventController";
import { AuthController } from "./controller/AuthController";
import { authenticate } from './middleware';
export const Routes = [{
    method: "delete",
    route: "/users/:id",
    controller: UserController,
    action: "remove",
    middleware: authenticate
}, {
    method: "put",
    route: "/users/:id",
    controller: UserController,
    action: "update",
    middleware: authenticate
}, {
    method: "get",
    route: "/receivers/:id",
    controller: ReceiverController,
    action: "one",
    middleware: authenticate
}, {
    method: "post",
    route: "/receivers",
    controller: ReceiverController,
    action: "create",
    middleware: authenticate
}, {
    method: "delete",
    route: "/receivers/:id",
    controller: ReceiverController,
    action: "remove",
    middleware: authenticate
}, {
    method: "put",
    route: "/receivers/:id",
    controller: ReceiverController,
    action: "update",
    middleware: authenticate
}, {
    method: "get",
    route: "/events/:id",
    controller: EventController,
    action: "one",
    middleware: authenticate
}, {
    method: "post",
    route: "/events",
    controller: EventController,
    action: "create",
    middleware: authenticate
}, {
    method: "delete",
    route: "/events/:id",
    controller: EventController,
    action: "remove",
    middleware: authenticate
}, {
    method: "put",
    route: "/events/:id",
    controller: EventController,
    action: "update",
    middleware: authenticate
}, {
    method: "post",
    route: "/auth/register",
    controller: AuthController,
    action: "register"
}, {
    method: "post",
    route: "/auth/login",
    controller: AuthController,
    action: "login"
}, {
    method: "post",
    route: "/auth/logout",
    controller: AuthController,
    action: "logout",
}];